### ISSUE TITLE
GOMAXPROCS ?

### ISSUE THREAD

**Issue by MikhailKlemin** [p886/go-parallel-http-requests#1]
Hi!
Is it changed recenlty, or still 
"In the current implementation of the runtime (Jan 2012) Go does not parallelize code by default,
only a single core or processor is dedicated to a Go-program, regardless of how many goroutines
are started in it; so these goroutines are running concurrent, they are not running in parallel: only
one goroutine is running at a time." 
To change that you have to alert GOMAXPROCS. If you have a lot of requests to slow web services, may be it could help.

**Comment by p886** [comment]
Hi there!

This code was just a test where I ported some Ruby code to Go for the sake of learning the language. It's not intended to be production-ready or even good code for that matter. You're right, while the HTTP requests run *concurrently*, they do not necessarily run *in parallel*. I didn't experiment with increasing GOMAXPROCS because this was just a very simple experiment.
